version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
        - 8000:8000
    volumes:
        - .:/backend
        - static_volume:/backend/var/django_static
    env_file:
        - .env
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  static_volume:
  postgres_data:
