# Generated by Django 3.2.8 on 2021-12-13 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwoSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('target', models.IntegerField()),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2)),
            ],
        ),
    ]
